include: package:lint/analysis_options.yaml

linter:
  rules:
    sort_constructors_first: true
    prefer_single_quotes: true
    public_member_api_docs: true
    always_put_required_named_parameters_first: false
